// src/actions/types.js
// LOGIN
export const FETCH_DATA_LOGIN_REQUEST = "FETCH_DATA_LOGIN_REQUEST";
export const FETCH_DATA_LOGIN_SUCCESS = "FETCH_DATA_LOGIN_SUCCESS";
export const FETCH_DATA_LOGIN_FAILURE = "FETCH_DATA_LOGIN_FAILURE";

// LOGOUT
export const FETCH_DATA_LOGOUT_REQUEST = "FETCH_DATA_LOGOUT_REQUEST";
export const FETCH_DATA_LOGOUT_SUCCESS = "FETCH_DATA_LOGOUT_SUCCESS";
export const FETCH_DATA_LOGOUT_FAILURE = "FETCH_DATA_LOGOUT_FAILURE";

// DASHBOARD
export const FETCH_DATA_PROFILE_REQUEST = "FETCH_DATA_PROFILE_REQUEST";
export const FETCH_DATA_PROFILE_SUCCESS = "FETCH_DATA_PROFILE_SUCCESS";
export const FETCH_DATA_PROFILE_FAILURE = "FETCH_DATA_PROFILE_FAILURE";

// REGISTER
export const FETCH_DATA_REGISTER_REQUEST = "FETCH_DATA_REGISTER_REQUEST";
export const FETCH_DATA_REGISTER_SUCCESS = "FETCH_DATA_REGISTER_SUCCESS";
export const FETCH_DATA_REGISTER_FAILURE = "FETCH_DATA_REGISTER_FAILURE";

// LOADING
export const SHOW_LOADING = "SHOW_LOADING";
export const HIDE_LOADING = "HIDE_LOADING";

// UPDATE PROFILE
export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAILURE = "UPDATE_PROFILE_FAILURE";
