// src/actions/types.js
// BUILD LOGIN TYPE
export const FETCH_DATA_LOGIN_REQUEST = 'FETCH_DATA_LOGIN_REQUEST';
export const FETCH_DATA_LOGIN_SUCCESS = 'FETCH_DATA_LOGIN_SUCCESS';
export const FETCH_DATA_LOGIN_FAILURE = 'FETCH_DATA_LOGIN_FAILURE';


// LOGOUT
export const FETCH_DATA_LOGOUT_REQUEST = 'FETCH_DATA_LOGOUT_REQUEST';
export const FETCH_DATA_LOGOUT_SUCCESS = 'FETCH_DATA_LOGOUT_SUCCESS';
export const FETCH_DATA_LOGOUT_FAILURE = 'FETCH_DATA_LOGOUT_FAILURE';


// DASHBOARD 
export const FETCH_DATA_PROFILE_REQUEST = 'FETCH_DATA_PROFILE_REQUEST';
export const FETCH_DATA_PROFILE_SUCCESS = 'FETCH_DATA_PROFILE_SUCCESS';
export const FETCH_DATA_PROFILE_FAILURE = 'FETCH_DATA_PROFILE_FAILURE';


