// src/actions/types.js
// BUILD LOGIN TYPE
export const FETCH_DATA_LOGIN_REQUEST = 'FETCH_DATA_LOGIN_REQUEST';
export const FETCH_DATA_LOGIN_SUCCESS = 'FETCH_DATA_LOGIN_SUCCESS';
export const FETCH_DATA_LOGIN_FAILURE = 'FETCH_DATA_LOGIN_FAILURE';

